### ISSUE TITLE
Error: Input required and not supplied: ocaml-compiler

### ISSUE THREAD

**Issue by fblanqui** [ocaml/setup-ocaml#630]
Hello. I have a CI problem since yesterday. See https://github.com/fblanqui/lib/runs/8142390869?check_suite_focus=true.
```
Run ocaml/setup-ocaml@v2
/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:4396
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: ocaml-compiler
    at Object.getInput (/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:4396:15)
    at Module.27196 (/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:95148:33)
    at __nccwpck_require__ (/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:121316:43)
    at /home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:121364:37
    at Object.<anonymous> (/home/runner/work/_actions/ocaml/setup-ocaml/v2/dist/index.js:121367:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```
My workflow file is https://github.com/fblanqui/lib/blob/master/.github/workflows/main.yml.
I don't know what to do. Some help would be very much appreciated.
Best regards, Frédéric.

**Comment by fblanqui** [comment]
Hi. It seems necessary to now fix the version of the ocaml compiler with
```
with:
          ocaml-compiler: 4.14.0
```
This was not the case before.

**Comment by smorimoto** [comment]
Yes, the problem is as the errors say and here are their documentation:
https://github.com/ocaml/setup-ocaml#inputs

**Comment by Leonidas-from-XIV** [comment]
I was hit by this as well. It's a bit disappointing to tag `ocaml-setup@v2` expecting the version to stay stable and then have it break anyway.

Maybe it would be nicer to just pick some OCaml version by default instead?
